### ISSUE TITLE
Checkout page first load Captcha validation Issue

### ISSUE THREAD

**Issue by vkharche91** [laminas/laminas-captcha#35]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.17.0

#### Summary

The Magento 2 Lumina reCAPTCHA implementation exhibits a problem during the checkout process. Specifically, the reCAPTCHA validation fails on the initial attempt, but succeeds when a new CAPTCHA is entered.

#### How to reproduce

Steps to Reproduce
1) Enter the CAPTCHA for the First Time:
    - Navigate to the checkout page.
    - Complete the CAPTCHA verification.
2) Enter Payment Details:
    - Fill in all required payment information.
3) Place Order:
    - Attempt to place the order.
4) Observe Issue:
    - An incorrect message is displayed, indicating that the CAPTCHA validation failed.
5) Re-enter CAPTCHA:
    - Enter a new CAPTCHA challenge.
6) Place Order Again:
    - Attempt to place the order again.
7) Verify Resolution:
    - The order should now process successfully, confirming that the CAPTCHA issue was resolved on the second attempt.

#### Expected behavior
The CAPTCHA validation should succeed on the first attempt, allowing the order to be placed without needing a second CAPTCHA entry.

**Comment by gsteel** [comment]
Can I suggest that you open this issue over at Magento. We will need a failing test case here before we'll consider it as a bug here rather than an issue with Magento or your environment.
